### ISSUE TITLE
Missing sections

### ISSUE THREAD

**Issue by germ** [monsonite/TTL-VGA-CPU#1]
Howdy, I'm working on a Gigatron compatible board at the moment and going over your schematic compared to the PDFs on hackaday. This stood out to me

> The files here are in a draft form and are missing some key control signals. They are for information only and do not currently represent a 100% complete transcript of Marcel's design.

Can you point me in a direction of what is missing?

**Comment by monsonite** [comment]
Hi Jeremy,

This is still a work in progress.  It was never going to be an exact
transcript because I wanted to make some changes to choice of component and
signal naming.

Marcel selected the pins carefully on some of the ALU  74HCT153 data
selectors and various 74HCT377 registers in order to produce a neater board
layout.  If you follow the bus order through some of the registers you will
notice that they do not read in numerical order.

 I wanted to move towards a more logical design based on '573, 574 and '541
bus oriented devices.

I have not completed this final choice of parts, as it will be based on
what is available in surface mount 74F series parts.

So in the meantime, I'm afraid that I cannot assist further.


regards


Ken

**Comment by germ** [comment]
No worries, thank you for laying the ground work. I’m trying to get in contact with him right now for the KiCad schematic and between the two of them I should be able to whack together a ROM compatible machine.

End goal is for a double sided 4layer PCB using surface mount packages. Ideally as small as possible without resorting to QFN. Might even swap out the VGA out to some sort of driver to HDMI and set up some a way to relay USB HID along.

Thank you again!

**Comment by monsonite** [comment]
Hi Jeremy,

I think if you use SOIC packages you can just about squeeze it onto a 10cm
x 10cm board. I did an initial placement and it looked about right.

With cheap pcbs available from China a SMT version would make a neat little
project.

I started splitting the design up to a series of modules - such as ALU,
Control Unit, Program Counter, Memory Access Unit etc - each of which could
be made on a standard board with 2.54mm header pins - say a standard 5cm x
5cm pcb and then plugged into a larger motherboard. The motherboard carries
all the bus wiring.

4 layer boards would be preferable for noise immunity - the existing design
will wipe out FM broadcast reception at about 5m away!

I have pushed the clock up to 10MHz using the 74HCT parts supplied, and up
to 11.0592 MHz with 74F parts.   Marcel is copying the ROM for me onto a
45nS access time 27C1024  which should allow up to 16MHz or so.  Beyond
16MHz, I think you need to execute the ROM code out of a fast RAM - and I
don't yet have a figure for the maximum carry propagation time of the ALU -
which may well become the limiting factor.

As the VGA generation takes about 75%+ of the processor's time it would be
nice to offload it onto another display controller.  There's a terminal
display that produces VGA from a Propeller chip and also either the
Gameduino 3 or terminal from James Bowman - both use the FT810 series LCD
controller - that can be fitted with D-A ladder resistors and produce a
24-bit VGA output  - up to 1024x768.  James and I got one working with a
13MHz clock which allows the higher resolution.

If I can spend a bit more time on the module idea - I'd be happy to
collaborate - just been a bit busy at work recently, and don't often feel
up to a whole lot more pcb layout work when I get home.

There's some interest on AnyCPU.org  forum for TTL computers - and a small
format Gigatron or modules to make up larger wordsize machines might be of
interest.


regards



Ken

**Comment by monsonite** [comment]
Hi Jeremy,

I finally got around this weekend  to completing the conversion of the
Gigatron TTL computer into Eagle CAD.

The IC numbers are the same as Marcel's design, and I have included the new
expansion option that allows for an 8-bit input and 8-bit output port -
mainly for  implementing SPI ports.

The design has been compacted so that it fits on a 200 x 100mm pcb - see
image. It could be further shrunk by switching to SMT parts.

I hope that this is of use to you

https://github.com/monsonite/Gigatron-CAD

regards


Ken

**Comment by germ** [comment]
Awesome! I reached out to Marcell and managed to get a hold of the GT schematic in the interim. It's good to see this exists, because now custom GT can be designed and all that.

>SMT Parts
That's exactly what I've been working on, check this out! (Ignore the routing, just wanted to make sure it was route-able).

![Selection_264](https://user-images.githubusercontent.com/10545/57274527-1a913600-708b-11e9-804e-48396908791d.png)

**Comment by monsonite** [comment]
Hi Jeremy,

That looks a neat board.

Did you get it down to 100mm x100mm - for cheap manufacture in China?

I decided to use dual common anode diodes for the instruction decoder
matrix to keep the space down.

If you are following the forum, Marcel got a board running at 15MHz with
74F.  He did a special ROM that gives an extra 200 cycles of vCPU time at
the end of each video line.  That really speeds up Tiny BASIC and
Mandelbrot by 5.5 X.

Now that I have a reference schematic in Eagle, I will have a look at a SMT
version - but retain the DIL ROM for compatibility reasons.


regards


Ken

**Comment by MikePinball** [comment]
Germ,
I know this is closed now. I have just started working on a SMD version too. I noticed there are some problems with monsonite's original board which I have been correcting. I plan to create a separate pull request. In the meantime would you be willing to share your Eagle files?

**Comment by germ** [comment]
@MikePinball Just a FYI, I was able to reach out to Marcell directly and get a schematic and whatnot. May be a good idea to give him a ping.

I can't share them as I agreed not to, or commercially produce clones :P

**Comment by MikePinball** [comment]
@Germ. The KiCad schematic seems to be readily available and then there is monsonite's version: https://github.com/monsonite/Gigatron-CAD. I have fixed a number of problems, converted everything to SMD, used 74F series chips, added a Tiny85 for a PS/2 keyboard, and reduced everything to a 4-layer 100mm square PCB including GND and VCC planes. I had to nest some SMD chips under the ROM and put a few on bottom to make everything fit. Ignore the layout stuff because it is the ugly Eagle autorouter and I need to move around some of the in/outs to improve the ease of connectivity. I sent in a trouble ticket so I can get my account activated to start posting on the forum.

![SMD_Gigitron_15](https://user-images.githubusercontent.com/41599843/72675557-b1e8be80-3a4b-11ea-8d87-a2b61d685746.jpg)
